@Server_HostAddress = http://localhost:5003

###

GET {{Server_HostAddress}}/api/players?team=Arsenal
Accept: application/json

###

###

GET {{Server_HostAddress}}/api/players?team=Everton
Accept: application/json

###
