@Server_HostAddress = http://localhost:5003

###

GET {{Server_HostAddress}}/api/seasons/719/teams/1/players
Accept: application/json

###

###

GET {{Server_HostAddress}}/api/seasons/719/teams
Accept: application/json

###
